// Generated by CoffeeScript 2.4.0
var handlebars, is_object_literal,
  indexOf = [].indexOf;

handlebars = require('handlebars');

({is_object_literal} = require('mixme'));

module.exports = function(context, options = {}) {
  var _render, _set, init, key, partial, proxify, proxy, value, visiting;
  // Default templated engine
  if (options.render == null) {
    options.render = function(source, proxy) {
      var template;
      template = handlebars.compile(source);
      return template(proxy, options.handlebars);
    };
  }
  if (options.partial == null) {
    options.partial = void 0;
  }
  // options.array ?= false
  // Tracking graph traversal
  visiting = [];
  // Work on properties
  _set = function(keys, value) {
    var i, j, key, len, results, search;
    search = context;
    results = [];
    for (i = j = 0, len = keys.length; j < len; i = ++j) {
      key = keys[i];
      if (i < keys.length - 1) {
        results.push(search = search[key]);
      } else {
        results.push(search[key] = value);
      }
    }
    return results;
  };
  // Render a template, the resulting `value` is placed in `keys`
  _render = function(keys, value) {
    var keys_as_string;
    keys_as_string = JSON.stringify(keys);
    // Update context with new value if not already visited
    if (indexOf.call(visiting, keys_as_string) >= 0) {
      throw Error(`Circular Reference: graph is ${[...visiting, [visiting[0]]].join(' -> ')}`);
    }
    visiting.push(keys_as_string);
    value = options.render(value, proxy);
    visiting.pop();
    _set(keys, value);
    return value;
  };
  // Clone the context by recursively converting it into proxies
  proxify = function(source, keys, partial) {
    var key, proxies, value;
    if ((Array.isArray(source) && options.array) || is_object_literal(source)) {
      // We can both store properties and indexes
      // This is the same as `proxies = []`
      proxies = {};
// Note, we can both traverse object and array
// this is the same as `for value, index in array`
      for (key in source) {
        value = source[key];
        if ((partial != null) && !partial[key]) {
          continue;
        }
        if (Array.isArray(value) && options.array) {
          proxies[key] = proxify(value, [...keys, key], ((partial != null) && is_object_literal(partial[key]) ? partial[key] : void 0));
        } else if (is_object_literal(value)) {
          proxies[key] = proxify(value, [...keys, key], ((partial != null) && is_object_literal(partial[key]) ? partial[key] : void 0));
        }
      }
    } else {
      throw Error('Unsupported');
    }
    return new Proxy(source, {
      get: function(target, key) {
        // Retrieve the value from context
        value = target[key];
        if ((partial != null) && !partial[key]) {
          // Return value without rendering if key is filtered by partial
          return value;
        }
        if (Array.isArray(value) && options.array) {
          return proxies[key];
        } else if (is_object_literal(value)) {
          return proxies[key];
        } else if (typeof value === 'string') {
          return _render([...keys, key], value);
        } else {
          return value;
        }
      },
      // Returned object if modified after being proxyfied
      set: function(target, key, value) {
        proxies[key] = value;
        target[key] = value;
        return true;
      }
    });
  };
  if (options.mutate) {
    for (key in context) {
      value = context[key];
      if ((Array.isArray(value) && options.array) || is_object_literal(value)) {
        partial = options.partial;
        partial = (partial != null) && is_object_literal(partial[key]) ? partial[key] : void 0;
        context[key] = proxify(value, [], partial);
      } else {
        context[key] = value;
      }
    }
    proxy = context;
  } else {
    proxy = proxify(context, [], options.partial);
  }
  // Trigger templating on every properties
  init = function(search, keys, partial) {
    var results;
    results = [];
    for (key in search) {
      value = search[key];
      if ((partial != null) && !partial[key]) {
        continue;
      }
      // String interpreted as a template
      if (typeof value === 'string') {
        results.push(_render([...keys, key], value));
      } else {
        // Note, array goes here as well and call `init` with the full array
        // init then loop through the array with `for` resulting
        // in the key as the index converted to a string
        results.push(init(search[key], [...keys, key], ((partial != null) && is_object_literal(partial[key]) ? partial[key] : void 0)));
      }
    }
    return results;
  };
  if (options.compile) {
    init(context, [], options.partial);
    return context;
  }
  // Return the result
  return proxy;
};
